export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const FETCH_USER = 'FETCH_USER';
export const STADIUM_FETCH_SUCCESS = 'STADIUM_FETCH_SUCCESS';
export const SET_USER = 'SET_USER';
