export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';
export const FIREBASE_LOGIN_SUCCESS = 'FIREBASE_LOGIN_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';

export const FETCH_USER = 'FETCH_USER';
export const STADIUM_FETCH_SUCCESS = 'STADIUM_FETCH_SUCCESS';

export const SET_USER = 'SET_USER';
export const SET_SELECTED_STADIUM = 'SET_SELECTED_STADIUM';
export const UPDATE_USER_SEATING = 'UPDATE_USER_SEATING';
